{{
    config(
        materialized = 'table',
        tags = ['finance', 'logistics']
    )
}}

WITH

ORDER_ITEMS_WITHOUT_REGION AS (
    SELECT 
        ORDER_ITEM.ORDER_ITEM_KEY,
        ORDER_ITEM.ORDER_KEY,
        ORDER_ITEM.ORDER_DATE,
        ORDER_ITEM.CUSTOMER_KEY,
        ORDER_ITEM.PART_KEY,
        ORDER_ITEM.SUPPLIER_KEY,
        ORDER_ITEM.ORDER_ITEM_STATUS_CODE,
        ORDER_ITEM.RETURN_FLAG,
        ORDER_ITEM.LINE_NUMBER,
        ORDER_ITEM.SHIP_DATE,
        ORDER_ITEM.COMMIT_DATE,
        ORDER_ITEM.RECEIPT_DATE,
        REGEXP_REPLACE(ORDER_ITEM.SHIP_MODE, '\\s', '_') AS SHIP_MODE,
        PART_SUPPLIER.COST AS SUPPLIER_COST,
        ORDER_ITEM.BASE_PRICE,
        ORDER_ITEM.DISCOUNT_PERCENTAGE,
        ORDER_ITEM.DISCOUNTED_PRICE,
        ORDER_ITEM.TAX_RATE,
        1 AS ORDER_ITEM_COUNT,
        ORDER_ITEM.QUANTITY,
        ORDER_ITEM.GROSS_ITEM_SALES_AMOUNT,
        ORDER_ITEM.DISCOUNTED_ITEM_SALES_AMOUNT,
        ORDER_ITEM.ITEM_DISCOUNT_AMOUNT,
        ORDER_ITEM.ITEM_TAX_AMOUNT,
        ORDER_ITEM.NET_ITEM_SALES_AMOUNT

    FROM
        {{ ref('order_items') }} ORDER_ITEM INNER JOIN {{ ref('part_suppliers') }} PART_SUPPLIER
    ON 
        ORDER_ITEM.PART_KEY = PART_SUPPLIER.PART_KEY AND 
        ORDER_ITEM.SUPPLIER_KEY = PART_SUPPLIER.SUPPLIER_KEY
)

SELECT 
    ORDER_ITEMS_WITHOUT_REGION.*,
    DIM_CUSTOMERS.REGION

FROM ORDER_ITEMS_WITHOUT_REGION LEFT OUTER JOIN {{ref('dim_customers')}} DIM_CUSTOMERS
ON ORDER_ITEMS_WITHOUT_REGION.CUSTOMER_KEY = DIM_CUSTOMERS.CUSTOMER_KEY
