{{config(materialized = 'table')}}


WITH 
ORDERS     AS (SELECT * FROM {{ ref('stg_tpch_orders') }}),
ORDER_ITEM AS (SELECT * FROM {{ ref('order_items') }}),


ORDER_ITEM_SUMMARY AS (
    SELECT 
        ORDER_KEY,
        SUM(GROSS_ITEM_SALES_AMOUNT) AS GROSS_ITEM_SALES_AMOUNT,
        SUM(ITEM_DISCOUNT_AMOUNT)    AS ITEM_DISCOUNT_AMOUNT,
        SUM(ITEM_TAX_AMOUNT)         AS ITEM_TAX_AMOUNT,
        SUM(NET_ITEM_SALES_AMOUNT)   AS NET_ITEM_SALES_AMOUNT
        
    FROM ORDER_ITEM
    GROUP BY ORDER_KEY
),


FINAL AS (
    SELECT 
        ORDERS.ORDER_KEY, 
        ORDERS.ORDER_DATE,
        ORDERS.CUSTOMER_KEY,
        ORDERS.STATUS_CODE,
        ORDERS.PRIORITY_CODE,
        ORDERS.CLERK_NAME,
        ORDERS.SHIP_PRIORITY,
        1 AS ORDER_COUNT,                
        ORDER_ITEM_SUMMARY.GROSS_ITEM_SALES_AMOUNT,
        ORDER_ITEM_SUMMARY.ITEM_DISCOUNT_AMOUNT,
        ORDER_ITEM_SUMMARY.ITEM_TAX_AMOUNT,
        ORDER_ITEM_SUMMARY.NET_ITEM_SALES_AMOUNT

    FROM ORDERS INNER JOIN ORDER_ITEM_SUMMARY
    ON ORDERS.ORDER_KEY = ORDER_ITEM_SUMMARY.ORDER_KEY
)


SELECT * FROM FINAL
ORDER BY ORDER_DATE