config-version: 2

name: 'randy_pitcher_workspace'
version: '2.0.0'

models:
  randy_pitcher_workspace:
    +materialized: table

    retail:
      +tags: 
        - retail
        - hourly
      marts:
        +materialized: table

    hello_world:
      +tags: 
        - hello_world
        - daily

    utils:
      +tags: 
        - utils
        - daily


        