config-version: 2

name: randy_pitcher_workspace
version: 1.5.0

models:
  randy_pitcher_workspace:
    retail:
      +tags: ['hourly', 'retail']
      +group: randy_pitcher_workspace__retail
      
      marts:
        +materialized: table
      
      staging:
        +access: private
        





















on-run-end: "{{ drop_ci_schemas(schemas, dry_run=False) }}"