config-version: 2

name: randy_pitcher_workspace
version: 1.5.0

models:
  randy_pitcher_workspace:
    retail:
      +tags: hourly
      marts:
        +materialized: table
        





















on-run-end: "{{ drop_ci_schemas(schemas, dry_run=False) }}"