config-version: 2

name: 'acme'
version: '1.0.0'

models:
  acme:
    +materialized: view

    retail:
      +tags: retail
      marts:
        +materialized: table

    hello_world:
      +tags: hello_world

    utils:
      +tags: utils


        