with source as (select * from {{ source('tpch', 'orders') }}),


RENAMED AS (
    SELECT
    
        O_ORDERKEY AS ORDER_KEY,
        O_CUSTKEY AS CUSTOMER_KEY,
        O_ORDERSTATUS AS STATUS_CODE,
        O_TOTALPRICE AS TOTAL_PRICE,
        O_ORDERDATE AS ORDER_DATE,
        O_ORDERPRIORITY AS PRIORITY_CODE,
        O_CLERK AS CLERK_NAME,
        O_SHIPPRIORITY AS SHIP_PRIORITY

    FROM SOURCE

)

SELECT * FROM RENAMED