WITH 

ORDERS    AS (SELECT * FROM {{ ref('stg_tpch_orders') }}),
LINE_ITEM AS (SELECT * FROM {{ ref('stg_tpch_line_items') }})

SELECT 
    LINE_ITEM.ORDER_ITEM_KEY,
    ORDERS.ORDER_KEY,
    ORDERS.CUSTOMER_KEY,
    LINE_ITEM.PART_KEY,
    LINE_ITEM.SUPPLIER_KEY,
    ORDERS.ORDER_DATE,
    ORDERS.STATUS_CODE AS ORDER_STATUS_CODE,
    LINE_ITEM.RETURN_FLAG,
    LINE_ITEM.LINE_NUMBER,
    LINE_ITEM.STATUS_CODE AS ORDER_ITEM_STATUS_CODE,
    LINE_ITEM.SHIP_DATE,
    LINE_ITEM.COMMIT_DATE,
    LINE_ITEM.RECEIPT_DATE,
    LINE_ITEM.SHIP_MODE,
    LINE_ITEM.EXTENDED_PRICE,
    LINE_ITEM.QUANTITY,
    LINE_ITEM.EXTENDED_PRICE/NULLIF(LINE_ITEM.QUANTITY, 0) AS BASE_PRICE,
    LINE_ITEM.DISCOUNT_PERCENTAGE,
    BASE_PRICE * (1 - LINE_ITEM.DISCOUNT_PERCENTAGE) AS DISCOUNTED_PRICE,
    LINE_ITEM.EXTENDED_PRICE AS GROSS_ITEM_SALES_AMOUNT,
    LINE_ITEM.EXTENDED_PRICE * (1 - LINE_ITEM.DISCOUNT_PERCENTAGE) AS DISCOUNTED_ITEM_SALES_AMOUNT,
    -1 * LINE_ITEM.EXTENDED_PRICE * LINE_ITEM.DISCOUNT_PERCENTAGE AS ITEM_DISCOUNT_AMOUNT,
    LINE_ITEM.TAX_RATE,
    (GROSS_ITEM_SALES_AMOUNT + ITEM_DISCOUNT_AMOUNT) * LINE_ITEM.TAX_RATE AS ITEM_TAX_AMOUNT,
    GROSS_ITEM_SALES_AMOUNT + ITEM_DISCOUNT_AMOUNT + ITEM_TAX_AMOUNT AS NET_ITEM_SALES_AMOUNT

FROM ORDERS INNER JOIN LINE_ITEM
ON ORDERS.ORDER_KEY = LINE_ITEM.ORDER_KEY

ORDER BY ORDERS.ORDER_DATE